version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: music_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: music_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/music_db
    volumes:
      - ./app:/app
    restart: unless-stopped

volumes:
  postgres_data: